version: '3.4'

services:
  ecommerceuireact:
    image: ecommerceuireact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
